--buy all limited furniture

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Queen Bed"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Queen Headstone Bed"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Twin Headstone Bed"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Neon orange",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Hanging Pumpkins"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Hanging Pumpkins"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Boo Lights"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Boo Lights"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Boo Lights"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Broom Light"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Broom Light"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Cabinet Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Cabinet Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Cabinet Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Coffin Pool Table"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Desk Scare"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Desk Scare"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Grandfather Clock"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Headstone I"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Headstone I"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Headstone II"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Headstone II"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Headstone III"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Headstone III"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Institutional white",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Lantern"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Obelisk"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Camo",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Potion"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Maroon",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Potion"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Bright blue",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Potion"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Pine Cone",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Spell Book"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dirt brown",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Spell Book"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Thin Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Thin Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Thin Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Wall Mounted Scare"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Wall Mounted Scare"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Cabinet Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Cabinet Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Cabinet Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Thin Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Thin Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark stone grey",
	["Quantity"] = 1,
	["Name"] = "Franken Savings Webbed Thin Bookshelf"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Institutional white",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Broken Mirror"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "White",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Candy Bowl"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Black",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Inflatable Pumpkin Stack"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Maroon",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Inflatable Spider"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Dark indigo",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Inflatable Spider"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Camo",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Inflatable Spider"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Furniture"
local ohTable2 = {
	["Color"] = "Institutional white",
	["Quantity"] = 1,
	["Name"] = "Witches' Warehouse Wall Web"
}

workspace.CommunicationRelays.Transaction.BuyItem:InvokeServer(ohString1, ohTable2)

